# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      
      # Install some package
      - name: Install luaunit
        run: luarocks install luaunit

      - name: Run parsel test
        run: |
          lua parsel.spec.lua -v
          lua parsel.spec.lua --output tap > parsel-spec-output.tap

      - name: Run luast parser test
        run: |
          pushd luast/
          lua lua_parser.spec.lua -v
          lua lua_parser.spec.lua --output tap > luast-spec-output.tap
          popd

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: parsel-spec-output.tap
        if: always()
